### ISSUE TITLE
How to make sources with spaces work flawlessly

### ISSUE THREAD

**Issue by amarakon** [hrsh7th/nvim-cmp#1223]
Let's say I have a source with items that have spaces. For example, the source is for font names and one example is "Times New Roman". If I use the default `get_keyword_pattern`, and I type "Times New", the completion menu will think I am just typing "New" because it does not think that "Times" is part of "New". To get around this, I can change `get_keyword_pattern`:

```lua
function source.get_keyword_pattern()
	return ".*"
end
```

This will make it work as intended, except if the line I am trying to write it on already has words in it. Then, if I type "Times New", nothing will pop up. I can sort of work around this by slightly changind `get_keyword_pattern` again:

```lua
function source.get_keyword_pattern()
	return "[A-Z].*"
end
```

Now, it will work **unless** the line already has an uppercase character.

Is there a way to make completion items with spaces work without any issues? Is that possible with the way nvim-cmp currently is, or would that need to involve changes in this plugin?

**Comment by hrsh7th** [comment]
I think the source should use `triggerCharacter` and `textEdit` that defined by LSP specification.

IMO, the keyword_pattern is no good for this situation because we can't determine the keyword position as you said.

I think you should compute keyword position from text before cursor.

**Comment by hrsh7th** [comment]
By the way, I probably can't give you a general answer to this question.
As you say, there is basically no "right" answer unless you clearly separate the identifiers.

Since the correct answer cannot be defined, the only way is to heuristically improve the usability. That is where ingenuity comes in.

For example, we can adopt @ as a trigger character and use @ as a delimiter.
cmp-emoji does something similar.

In any case, this is not a problem that can be supported by the main body, but one that should be devised by the source creator.

Translated with www.DeepL.com/Translator (free version)

_deepl translated_
