### ISSUE TITLE
[Question] How to make the preselected item always on the top of the suggestion list.

### ISSUE THREAD

**Issue by nanozuki** [hrsh7th/nvim-cmp#153]
Here is my setup:

```lua
local function setup()
	local exists, cmp = pcall(require, "cmp")
	if not exists then
		return
	end
	cmp.setup({
		completion = {
			completeopt = "menu,menuone,noinsert",
		},
		sorting = {
			priority_weight = 1,
		},
		snippet = {
			expand = function(args)
				vim.fn["vsnip#anonymous"](args.body)
			end,
		},
		documentation = {},
		mapping = {
			["<C-p>"] = cmp.mapping.select_prev_item(),
			["<C-n>"] = cmp.mapping.select_next_item(),
			["<CR>"] = cmp.mapping.confirm({ select = true }),
			["<Tab>"] = cmp.mapping(function(fallback)
				if vim.fn.pumvisible() == 1 then
					vim.fn.feedkeys(termcode("<C-n>"), "n")
				elseif vim.fn["vsnip#available"]() == 1 then
					vim.fn.feedkeys(termcode("<Plug>(vsnip-expand-or-jump)"), "")
				elseif check_back_space() then
					vim.fn.feedkeys(termcode("<Tab>"), "n")
				else
					fallback()
				end
			end, {
				"i",
				"s",
			}),
			["<S-Tab>"] = cmp.mapping(function(fallback)
				if vim.fn.pumvisible() == 1 then
					vim.fn.feedkeys(termcode("<C-p>"), "n")
				elseif vim.fn["vsnip#available"]() == 1 then
					vim.fn.feedkeys(termcode("<Plug>(vsnip-jump-prev)"), "")
				else
					fallback()
				end
			end, {
				"i",
				"s",
			}),
		},
		sources = {
			{ name = "nvim_lsp" },
			{ name = "vsnip" },
			{ name = "path" },
			{ name = "buffer" },
		},
	})
end
```

And I found, in some situations, the preselected item is not on the top of the suggestion list:

![image](https://user-images.githubusercontent.com/4208028/132119723-3b813ee8-e122-4ea4-93c3-9d4826dd7250.png)

Is there a method to fix this?

**Comment by nanozuki** [comment]
The preselected result is what I want, but not on the top.

**Comment by hrsh7th** [comment]
It's expected behavior. same as VSCode or coc.nvim.

```lua
local preselecy = function(entry1, entry2)
  local preselect1 = entry1.completion_item.preselect or false
  local preselect2 = entry2.completion_item.preselect or false
  if preselect1 ~= preselect2 then
    return preselect1
  end
end
```

You can add this to `sorting.comparators`.

BTW, I don't know other completion engine that customizable this behavior. (it's advanced comfiguration)

**Comment by nanozuki** [comment]
Thanks for the wonderful answer.

> It's expected behavior. same as VSCode or coc.nvim.

I don't why, the result is a little different in my vscode: 

![image](https://user-images.githubusercontent.com/4208028/132121533-61279b6b-aa19-49d4-a35b-6278b47f6244.png)

The result and order in each kind are actually the same. But the order of kinds is different.

**Comment by hrsh7th** [comment]
Yes. nvim-cmp sorting is not same as VSCode.
For example, VSCode sorting is alphabeticsl order but nvim-cmp sort by abbr length.

**Comment by hrsh7th** [comment]
@nanozuki This issue can be closed, right?

**Comment by nanozuki** [comment]
> @nanozuki This issue can be closed, right?
Yes, I got the answer.

**Comment by kamilez** [comment]
@hrsh7th I would like to avoid opening new issue since I am facing almost the same problem and context fits so I'll write it here.

The problem is the same - selected item is not at the top of menu - and adding custom comparator fixes this problem but not quite. It just moves selected item to the top leaving all other most accurate completions where they were. Here is example:
![image](https://user-images.githubusercontent.com/16545480/147934037-5996f3b4-8de6-4dc6-bfe6-09d166bda7b4.png)
In this case what I would expect are all structure fields at the beginning. I've been trying with multiple variations of comparators and still have no idea how to fix it. In contrary, when I use omnifunc to complete the order seems to be more accurate but then I loose some of the features from cmp like replacing provided string with snippet from lsp (in gopls value.print! and etc)
![image](https://user-images.githubusercontent.com/16545480/147934945-0743118d-7e05-41b5-88c8-cfe3b8d720f3.png)

How can I reproduce this omnifunc completion order in cmp?
