### ISSUE TITLE
Confirm completion repeat match/result mutiple times

### ISSUE THREAD

**Issue by n3wborn** [hrsh7th/nvim-cmp#343]
Hi ! 

As I build neovim and update plugins everyday, I'm quite sure this behaviour is recent. 
When I want to change a previous word, I go back to the end of it, delete some chars and then hit `<C-space>` to trigger completion. Then, when adding letters and then confirming the best match, instead of replacing the word it will append it to the current word (as you can see in the capture)

This happens only when I trigger completion before, not when I type normally. I was quite sure my config was ok,  but as I add these *behavior = ...* in cmp.mappings maybe I did a mistake. If yes, really sorry, my bad.

Hope I was clear enough in my explanations. If my config is needed it can be found [here](https://github.com/n3wborn/nvim/blob/main/lua/modules/plugins/cmp.lua)

EDIT : This happens even when I'm inserting normally (not triggering completion or replacing something)

![image](https://user-images.githubusercontent.com/10246722/137001989-fb7d2383-a34a-465a-a7f5-ea02705a8dfd.png)

**Comment by djdv** [comment]
For what it's worth, I was _not_ having this problem until recently with the built in mappings.
I'm not positive but I think 071c08fcc9ba04ac779fba2353f90626b05c4ebe was working fine, and the commits between then and HEAD from today (49acc848531b8cbe051c598dddd0cc46ec64f4b4) started causing issues.

However, even previously I encountered an issue when defining my own mappings.
I wanted <kbd>space</kbd> to trigger the completion if the menu is up and an item is selected (otherwise it just acts like normal). In addition, I wanted a space to still be typed if expanding non-snippets.

It almost worked the way I expected it too, however it was inserting duplicate characters upon completion. Similar to how `<cr>` is doing now.

Previously, I decided to implement the mapping manually to see which step in the chain was causing the issue.
I noticed that if I put the feedkeys calls (via `fallback`) in the confirm callback, I was not seeing this duplication problem.
I'm wondering if there is some kind of ordering or asynchronous problem going on.

From my config:
```lua
['<Space>'] = cmp.mapping(function(fallback)
	if cmp.visible() then
		-- TODO: figure out why this bugs out, could be upstream
		--`function`<space> turns into `ffunction *completion*`
		-- `thi`<space> turns into `tthing`, etc.
		--if cmp.confirm({
		--	behavior = cmp.ConfirmBehavior.Replace,
		--}) then
		--	return
		--end
		--fallback()
		-- NOTE: Placing the feedkeys call in the callback works as expected.
		local e = cmp.core.view:get_selected_entry()
		if e then
			cmp.core:confirm(e, {
				behavior = cmp.ConfirmBehavior.Replace,
			}, function()
					cmp.core:complete(cmp.core:get_context({ reason = cmp.ContextReason.TriggerOnly }))
					-- Only add the space when not expanding a snippet. (So for text, variables, buffer, etc.)
					if e:get_kind() ~= types.lsp.CompletionItemKind.Snippet then
						fallback()
					end
				end)
			return true
		end
	end
	fallback()
end, { "i", "s" }),
['<CR>'] = cmp.mapping.confirm({
	behavior = cmp.ConfirmBehavior.Replace,
	select = false,
}),
```

This still works fine with <kbd>space</kbd> but the default mapping for `<cr>` is no longer working.

**Comment by ahmedmohamed-hue** [comment]
I'm having the same issue here with NVIM v0.5.0 built from source.

**Comment by hrsh7th** [comment]
Sorry. I'm busy until this weekends. I'll look into it.

**Comment by tinytub** [comment]
meet same issue
and update to https://github.com/hrsh7th/nvim-cmp/commit/c658cc52dfe64bd5712ef3fb012d45d3553d2ad0 also have the problem

**Comment by Balrrach** [comment]
I have the same issue but only in markdown files and the update hasn't fixed it. I don't have the option `set backspace=0` enabled so I don't know what it could be.
NVIM v0.7.0. My configuration is:
```lua
local cmp = require'cmp'
local lspkind = require('lspkind')

cmp.setup({

formatting = {
	format = 
	function(entry, vim_item)
		vim_item.kind = lspkind.presets.default[vim_item.kind]
		return vim_item
	end
},

	completion = {keyword_length = 1,},

	snippet = {
		expand = function(args)
		-- For `vsnip` user.
		vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` user.

		-- For `luasnip` user.
		-- require('luasnip').lsp_expand(args.body)

		-- For `ultisnips` user.
		-- vim.fn["UltiSnips#Anon"](args.body)
	end,
	},

mapping = {
	['<C-d>'] = cmp.mapping.scroll_docs(-4),
	['<C-f>'] = cmp.mapping.scroll_docs(4),
	['<C-Space>'] = cmp.mapping.complete(),
	['<C-e>'] = cmp.mapping.close(),
	['<CR>'] = cmp.mapping.confirm({ select = true }),
	['<C-j>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' }),
	['<C-e>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' }),
	-- ['<Tab>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' }),
	-- ['<Tab>'] = cmp.mapping.confirm({ select = true }),
	['<Esc>'] =
	function(fallback)
		cmp.mapping.abort()
		fallback()
	end,
	-- ['<CR>'] = function()
	-- if not cmp.confirm({ select = false }) then
	-- vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<CR>', true, true, true), 'n', true)
	-- ['<CR>'] = vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<CR>', true, true, true), 'n', true),
},

sources = cmp.config.sources(
{
	{ name = 'nvim_lsp' },
	{ name = 'cmp_tabnine' },
	{ name = 'vsnip' }, -- For vsnip users.
	-- { name = 'luasnip' }, -- For luasnip users.
	-- { name = 'ultisnips' }, -- For ultisnips users.
	-- { name = 'snippy' }, -- For snippy users.
},
{ { name = 'buffer' }, }
)

})
```
