### ISSUE TITLE
Re-design configuration schema (or approach)

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-cmp#4]
I've no satisfied the current configuration schema... help or opinions are wanted.

**Comment by Shougo** [comment]
If completion plugin include sources, the issues will be hard to maintain.
Because the issues includes many source problems like current nvim-cmp issues.

>Not necessarily include all of the sources that nvim-compe has by default but at least something basic like buffer and path source of completion to have a more "out the box" experience. 

Yes.  It can.  But what is the basic?  Some people say "lsp!" and some people say "I don't like buffer source!".  Oh, bikeshedding arguments.
I think it is the best that none of sources are included.

**Comment by rafamadriz** [comment]
> If completion plugin include sources, the issues will be hard to maintain.
> Because the issues includes many source problems like current nvim-cmp issues.

got it, that completely makes sense.  

> Yes. It can. But what is the basic? Some people say "lsp!" and some people say "I don't like buffer source!". Oh, bikeshedding arguments.

yes that can be problematic on what can be considered as "basic", people have their own preferences.

**Comment by Jesse-Bakker** [comment]
Looking at the example configuration, I have two notes:

1. I do not think a plugin setup should concern itself with setting mappings. Neovim already has good facilities to create mappings and having a different approach in a plugin smells like feature creep.
2. In the example, sources are defined using their "name", e.g.: `sources = {
      { name = 'buffer' }
    }`. It is not clear to me how these are resolved, but it might be nice to just use the `source` item as defined in the "Source creation" part of the README instead.

**Comment by akinsho** [comment]
> I do not think a plugin setup should concern itself with setting mappings. Neovim already has good facilities to create mappings and having a different approach in a plugin smells like feature creep.

I don't think this is feature creep there are quite a lot of examples of plugins doing this `gitsigns`, `nvim-tree`, `diffview.nvim`, `neoscroll`, `orgmode.nvim`, `fugitive` tbh I'd say optionally applying mappings is a very common pattern especially since currently you still have to map to strings unless you've developed something custom in your `init.lua` whereas this seems to take lua functions directly which is much easier to use for the majority of people who don't have these workarounds in place already.

**Comment by hrsh7th** [comment]
IMO, I don't like the plugin apply mappings by itself. I think the plugin should provide `<Plug>` mapping instead.

But I decided to provide `setup { mapping = { ... } }` API in nvim-cmp.

The reason is that I received a lot of issues with this.

https://github.com/hrsh7th/nvim-compe/issues/103
https://github.com/hrsh7th/nvim-compe/issues/74
https://github.com/hrsh7th/nvim-compe/issues/121
https://github.com/hrsh7th/nvim-compe/issues/171
https://github.com/hrsh7th/nvim-compe/issues/361
https://github.com/hrsh7th/nvim-compe/issues/425

**Comment by numToStr** [comment]
In regards to maintenance, Why not make a Github organization under the name of `nvim-cmp` and develop all the plugins and sources there? Just like `nvim-lua`.

**Comment by hrsh7th** [comment]
done for now.
I can create `nvim-cmp` organization but I hadn't ever do it.

If you have strong opinion about it, please create separated issue.
