### ISSUE TITLE
Get window config/options or identify cmp window(s)

### ISSUE THREAD

**Issue by HudsonMC16** [hrsh7th/nvim-cmp#430]
I'm trying to write some little helpers which will spawn other windows around my cursor, but I don't want them to interfere with the cmp windows, so basically open on the opposite side of the cursor than cmp (for example). I know the plugin has an API for determining if the menu is open, but I can't figure out a good way to get the position, anchor, offsets, etc. of the floating cmp window(s). I may be missing something, but it doesn't appear cmp identifies the floating windows it spawns with specific ftypes or btypes either. Do you have any suggestions or is this a new feature?

**Comment by dmitmel** [comment]
I don't think this is a good solution. Nowadays more and more Nvim plugins use floating windows for their functionality, so it would be useful to distinguish between cmp's and other's usages of floats. I personally need this because I configured the buffer source to read words from all other open buffers, but I must ignore the buffer cmp uses for its window because otherwise words get stuck in the cache and never get deleted. For that I poke at internals a bit and read the value of `cmp.core.view.custom_entries_view.entries_win.win`, but it would be very useful if this (along with getting the buffer that the completion window uses) exposed in some way, or at least the buffer and window would be, for instance, marked with `let b:cmp_menu = 1` and `let w:cmp_menu = 1` (respectively).

**Comment by hrsh7th** [comment]
I can add window variable. But I think we shouldn't add new API for getting window position and sizes.

**Comment by HudsonMC16** [comment]
> I can add window variable. But I think we shouldn't add new API for getting window position and sizes.

I think this is a good solution. If cmp can just identify it's windows with a specific btype, ftype, or buffer/window scoped variable like you mention, I think that follows the pattern many other plugins use and is a lot simpler than adding a new API feature.
