### ISSUE TITLE
`def __init__()` from Python is being completed incorrectly

### ISSUE THREAD

**Issue by lumbo7332** [hrsh7th/nvim-cmp#47]
Not sure if this is the right spot to report this bug, so please tell me if it isn't.

When trying to complete `def __init__()` the first option completes to `def __init__(self) -> None:^@    super().__init__()`. I'm guessing the `^@` is supposed to be converted to a newline. I'm using the `pyright` language server.

**Comment by uga-rosa** [comment]
This is not a completion candidate provided by pyright. It is provided by another source, please show me vimrc.
Also, what you want to do can probably be achieved with a snippet engine. Multi-line completion is a different principle and requires a snippet engine (such as vsnip or LuaSnip). Since pyright does not provide snippets, you may want to define your own or use [friendly snippet](https://github.com/rafamadriz/friendly-snippets) or something similar.

**Comment by uga-rosa** [comment]
![image](https://user-images.githubusercontent.com/82267684/130374558-d3e583ba-1ab1-45dc-a947-9890ae0fece3.png)
![image](https://user-images.githubusercontent.com/82267684/130374565-a3760970-fb05-4449-8331-dc17e131c633.png)
I just tried, `^@` is converted to a newline. Is it because of the newline or character encoding settings? Without looking at init.vim, it is hard to tell what is causing the problem.

**Comment by lumbo7332** [comment]
Ohhh. I have to press enter. I was just moving on once it selected it as the first option. Could it be made to convert the symbol to a newline if it's automatically selected as the first option?

**Comment by uga-rosa** [comment]
There is an option that automatically selects the first candidate when you press enter when the list of candidates is displayed.

**Comment by lumbo7332** [comment]
I'll give that a shot. Thank you!

**Comment by hrsh7th** [comment]
I will improve temporary text (maybe I will cut off the text till \n)
