### ISSUE TITLE
Macro tracking issue

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-cmp#564]
#551
#558

**Comment by hrsh7th** [comment]
I think we can't support macro correctly. (If anyone have any ideas, please let me know.

1. The user press `<CR>` to confirm the selected item
2. The `<CR>` will be added to the macro register literally
3. The user executes the macro. the `<CR>` will add the new line (because the selected entry is nothing in executing macro)

I think the nvim-cmp should stop working in executing the macro.

**Comment by eckon** [comment]
Hey, firstly thanks for the great work @hrsh7th.

Then to my question: is there currently a way to deactivate this behavior? Meaning stopping nvim-cmp from executing in the macro as you mentioned?

Currently this prevents me from using any macros that include the symbols mentioned in #551 `,`, `.`, `(` (and I guess the same for #558 `<CR>` which is not as bad for me personally).
This I need from time to time, at least often enough that I can not ignore it, and I would be surprised if I am the only one (unless no one is using macros for refactoring anymore).

As far as I can remember `coc.nvim` also never completed correctly by itself in a macro (maybe even didn't do anything), which was fine, because it had no side-effects on the normal macro and I could just write the macro as if I did not have the completion.

I would like to help, but sadly I do not know how to fix this. Maybe if others still need this behavior and as a quickfix until someone else figured out a better way, add a flag to disable macro execution?

**Comment by smjonas** [comment]
By the way, the `RecordingEnter` and `RecordingLeave` events have recently been added to Neovim. I think they will make things easier to implement now (maybe add an option to disable cmp when a macro is recorded?).

**Comment by eckon** [comment]
@dmitmel good to know, sadly enabling/disabling cmp does not seem to work. I am guessing it is because the `imaps` are already set at the time of the recording.

![image](https://user-images.githubusercontent.com/40291209/148221655-9e8eed4c-2915-4df4-8455-63d472743f05.png)
etc.. (through `:imap<CR>`)

The events allow for a (at least for me) dirty way of unsetting these mappings when starting the macro, and it seems like nvim-cmp just rebinds them afterwards (but could be that this results in other problems - didnt try it out much yet).


In case anyone is interested (use on your own risk):
```vim
augroup HandleNvimCmpOnMacro
  autocmd!
  autocmd RecordingEnter * for symbol in [',', '.', '('] | execute('silent! iunmap ' . symbol) | endfor
augroup END
```

Of course if there is a better solution then I would be glad to through this snippet away.

**Comment by mikehaertl** [comment]
@hrsh7th Is this issue solved? Or why was it closed? What is the solution? I still have the problem that I can not record any linebreaks in my macros when I have this enabled:

```
      ['<CR>'] = cmp.mapping.confirm({ select = false }),
```

**Comment by mikehaertl** [comment]
Probably handled in #800 now.
