### ISSUE TITLE
Please provide a list of source names for the `sources = {}` object that match the plugin name

### ISSUE THREAD

**Issue by David-Else** [hrsh7th/nvim-cmp#61]
In the README it seems that the sources need to be guessed from the plugin name?

`hrsh7th/cmp-nvim-lsp` = `nvim_lsp`
`hrsh7th/cmp-path` = `path`

It seems confusing. If I enter the wrongly guessed name, for example,  `sources = { { name = nvim-lsp } }` then it gives no error. How can I be sure of the correct name? Can an error be added?

**Comment by arcticlimer** [comment]
Indeed this is quite irregular, but the plugins themselves set their names to compe, such as in https://github.com/andersevenrud/compe-tmux/blob/881b5255e12fef6c28e1039f4afeb77626205b24/after/plugin/compe_tmux.vim#L7.
I don't know if there is a better way, but I just go to the source of the plugin and check how it names itself.

**Comment by andersevenrud** [comment]
I was having these exact thoughts today when migrating to nvim-cmp. The mental stripping of the `cmp-` prefix if fine, but having some sort of uniform naming scheme would be great!

**Comment by hrsh7th** [comment]
Do we need `CmpStatus` command?

**Comment by SmiteshP** [comment]
> Do we need `CmpStatus` command?

A checkhealth functionality would be great to tell us which sources are working.

**Comment by uga-rosa** [comment]
It seems to me that it would be a simple matter to have the sources clearly stated in the README of each source...

**Comment by hrsh7th** [comment]
I've added source name documentation to the all of my managed cmp-sources.

**Comment by jason0x43** [comment]
It would also be useful for `nvim-cmp` to throw an error or print a message if it's configured with an invalid source. I spent a while this morning trying to figure out why I wasn't getting LSP completions. The problem was that I had given my source name as `nvim-lsp` rather than `nvim_lsp`, and `nvim-cmp` didn't give me any indication (that I saw) that the config was invalid.

**Comment by kuon** [comment]
I agree with @jason0x43 . 

I had ` name = "cmp-buffer"` instead of `name = "buffer"` in my config and I was going crazy not understanding what was wrong.

Best thing would be an error when vim launch (full crash fix your config), but if that is not possible (maybe lazy evaluation?) having an error when the plugin tries to autocomplete would also work.

**Comment by hrsh7th** [comment]
Yes. I'm considering it but sometimes the user set up as lazyloading. So we should care about it.

**Comment by rumpelsepp** [comment]
Wouldn't it make sense to include some basic default sources in this repo? The user could overwrite them in the config if he doesn't like it. It is really confusing to search and maintain all these plugins on Github. I figure that at least `buffer` and `lsp` is wanted by most people. The sources repos are also very small; I see no practical reason for splitting them across multiple repos.

**Comment by hrsh7th** [comment]
First, I can understand what you said. But I wouldn't include any sources as built-in for maintenance reason.

I don't know the criteria for separating sources.
For example, the tag source looks good with built-in.
nvim-compe was contained only paths, buffers, LSPs, and vsnip sources that were built-in.

**Comment by rumpelsepp** [comment]
>  But I wouldn't include any sources as built-in for maintenance reason.

That's my point. Then you (as you seem the maintainer of these sources as well) have e.g. 3 different repos, with 3 different bug trackers with 3 different merge request trackers. The burden on your side is increased and on the user, since there are multiple plugins which need to be configured, tracked etc.

**Comment by hrsh7th** [comment]
At this point, I feel that it is rather easier to maintain. The cmp-buffer / cmp-path issue has been created and resolved in the appropriate repository.

(google translated).

**Comment by hrsh7th** [comment]
I've added the `:CmpStatus` command.
