### ISSUE TITLE
Disable source for certain filetypes

### ISSUE THREAD

**Issue by shinzui** [hrsh7th/nvim-cmp#666]
Sorry if this has been answered elsewhere, but I couldn't find a way to disable a source for a particular file type. What's the API, in general, to dynamically configure sources? My use case is that I want to disable the `emoji` source in `Haskell` and `PureScript` since `:` is commonly used.

**Comment by dmitmel** [comment]
> What's the API, in general, to dynamically configure sources?

You can just call `cmp.setup` or its variants repeatedly. E.g.:

```lua
-- ftplugin/haskell.lua
cmp.setup.buffer({
  sources = { ... }
})
```

The problem is that `cmp.setup` doesn't perform any configuration merging, so a call to it or `cmp.setup.buffer` replaces the configuration entirely (or not, I think it is done per-section. So `sources`, `completion`, `documentation` etc, the top-level keys, are separate sections). I don't do this myself, but if I were you, I'd do something like this:

```lua
-- ftplugin/haskell.lua
local cmp = require('cmp')
local sources = cmp.get_config().sources
for i = #sources, 1, -1 do
  if sources[i].name == 'emoji' then
    table.remove(sources, i)
  end
end
cmp.setup.buffer({ sources = sources })
```

**Comment by shinzui** [comment]
Thanks, @dmitmel. I'll give a try.
