### ISSUE TITLE
[Question]: Menu Appearance

### ISSUE THREAD

**Issue by johnstonbl01** [hrsh7th/nvim-cmp#671]
First - really appreciate this project, thank you for working on this as a hobby! 🙏 

I'm relatively new to vim / lua, so this may be obvious. Googling didn't help much, so here I am. Apologies if I overlooked the answers to these somewhere!

- Is it possible to modify the border color of the `nvim-cmp` menu? It looks like there is a `CmpItemMenu`, but I haven't been able to get the border color to change.
- Is it possible to add padding to the menu so that the suggestion doesn't bump up against the edge?

Thank you!

**Comment by dmitmel** [comment]
> Is it possible to modify the border color of the `nvim-cmp` menu? It looks like there is a `CmpItemMenu`, but I haven't been able to get the border color to change.

No, see #472

> Is it possible to add padding to the menu so that the suggestion doesn't bump up against the edge?

Do you mean the vertical or the horizontal padding? I think horizontal already exists, but vertical can be considered part of #472.

**Comment by johnstonbl01** [comment]
👍 Thank you for the swift reply!
I was actually thinking of both. Is there a current way to adjust the horizontal padding?

Example of what it currently looks like for me: 
<img width="218" alt="Screen Shot 2021-12-27 at 4 56 56 PM" src="https://user-images.githubusercontent.com/1808501/147512326-06e6e53e-ccb1-48bc-8164-e333fdedcc35.png">

There is definitely some padding there, but was curious if I could essentially double it.

**Comment by max397574** [comment]
perhaps possible with the formatting option

**Comment by hrsh7th** [comment]
```lua

cmp.setup {
  formatting = {
    format = function(entry, vim_item)
      vim_item.abbr = ' ' .. vim_item.abbr
      vim_item.menu = (vim_item.menu or '') .. ' '
      return vim_item
    end
  }
}
```

**Comment by johnstonbl01** [comment]
> 

Thank you!

**Comment by techtycho** [comment]
For the border color, I was able to change my border color with this approach:

```
window = {
    completion = cmp.config.window.bordered({
      winhighlight = "Normal:Normal,FloatBorder:BorderBG,CursorLine:PmenuSel,Search:None",
    }),
},
```

The highlight class for the border is `BorderFloat`. In [`window.lua`](https://github.com/hrsh7th/nvim-cmp/blob/9897465a7663997b7b42372164ffc3635321a2fe/lua/cmp/config/window.lua) the default border highlight class is `Normal`, this will set the `guibg` to the background color of the editor, making the background transparent, and the `guifg` is set to a white grayish color. You can't modify the `Normal` class because this will apply to the entire editor.

Instead, give it a new class with a unique name. The `window.bordered()` function in `window.lua` has an `opt` parameter, in the above code block, you can see that you can give it a table as an argument which overrides the default options. You only want to change `winhighlight`, give it a string like the above with `FloatBorder` set to a class with a unique name of your own. Now to change the color, just use Vimscript:

```
vim.cmd "highlight! BorderBG guibg=NONE guifg=#00ff00"
```

Put this at the end of the file, as you can see, I set it to green, change it to any color you want, you can also change the bg color but I suggest leaving it to `NONE` to make the bg transparent. You can also set other options.

**Comment by bluebrown** [comment]
shouldn't the class be NormalFloat, by default, to align with the rest of vim?

**Comment by fooness** [comment]
> shouldn't the FloatBorder class be FloatBorder, by default, to align with the rest of neovim?

Yes, please.

**Comment by gokberkgunes** [comment]
I agree with what @bluebrown said, FloatBorder class should be FloatBorder to match the rest of the neovim floating borders. For example, vim.diagnostic.config (vim.diagnostic.open_float) sets border to FloatBorder.
