### ISSUE TITLE
Documentation Request: Source Listing Page

### ISSUE THREAD

**Issue by p0da** [hrsh7th/nvim-cmp#837]
### Description

Would you consider allowing the creation of markdown page/wiki page/anything else that would have a listing of sources along with a short description to improve source discoverability (nvim-cmp topic is already kinda polluted and only relevant to gh hosted sources). Source authors could then make PRs to add their source.

**Comment by smjonas** [comment]
That is a great idea, I think a Wiki page would be good because everyone can simply edit it without hrsh7th having to deal with too many PRs. It would also be useful to sort the sources by some categories or at least alphabetically (although I am not too sure which categories might make sense except obvious ones like "Snippet engines").

**Comment by smjonas** [comment]
I have created a Wiki page with most of the sources that use the [nvim-cmp](https://github.com/topics/nvim-cmp) GitHub tag. You can find it [here](https://github.com/hrsh7th/nvim-cmp/wiki/List-of-sources). Edits / improvements are welcome! Although the list is not 100% complete, I think this issue can be closed for now :)
